### ISSUE TITLE
🛴 Check other templates here on Github

### ISSUE THREAD

**Issue by jonjoncardoso** [jonjoncardoso/data-science-workflow#46]
There's no need to reinvent the wheel. If other public templates here on Github already contain useful actions, and their license allow, we could get a few ideas from there.

### Tasks

- [ ] Map what is out there ( example: https://github.com/rochacbruno/python-project-template)
- [ ] Identify what automation other people have built in their templates
- [ ] Identify which new features we could have in our template

**Comment by jonjoncardoso** [comment]
Relevant templates I found:

- [Python project template](https://github.com/rochacbruno/python-project-template)
- [Template repository with Github actions](https://github.com/dslp/dslp-repo-template)
- [Azure TDSP Project Template](https://github.com/Azure/Azure-TDSP-ProjectTemplate)
- [makcedward/ds_project_template](https://github.com/makcedward/ds_project_template)
- [A cookiecutter template](https://github.com/khuyentran1401/data-science-template)
- [NeowayLabs template](https://github.com/NeowayLabs/data-science-template)
- [A conda and Docker-based template](https://github.com/KAUST-CTL/python-data-science-project)
- [equinor's cookiecutter template](https://github.com/equinor/data-science-template)
- [Gov UK cookiecutter template](https://github.com/best-practice-and-impact/govcookiecutter)
- [AWS cookiecutter template](https://github.com/aws-samples/python-data-science-template)
